[workspace]
members = [
    "bindings",
    "macros",
    "noop",
    "hashing",
]

[profile.release]
debug = true
opt-level = 3
lto = true

[patch.crates-io]
getrandom = { git="https://github.com/kaimast/getrandom", branch="open-lambda" }
